services:
  database:
    image: postgres:18
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_USER: 'youruser'
      POSTGRES_DB: 'march'
      PGDATA: /var/lib/postgresql/18/data
    volumes:
      - pgdata18:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'youruser', '-d', 'march']
    networks:
      - app_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: start
    environment:
      LM_STUDIO_BASE_URL: 'http://host.docker.internal:1234/v1'
      NODE_ENV: production
      CONNECTION_STRING: 'postgresql://youruser:yourpassword@database:5432/march'
    env_file:
      - ./apps/backend/.env
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
networks:
  app_network:

volumes:
  pgdata18: {}
