services:
  agent:
    build:
      context: /Users/ezzabuzaid/Desktop/mo/pm
      dockerfile: /Users/ezzabuzaid/Desktop/mo/pm/Dockerfile
    platform: linux/amd64
    environment:
      PORT: 3000
      NODE_ENV: development

      CONNECTION_STRING: 'postgresql://youruser:yourpassword@database:5432/march'
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3100,http://localhost:5173,http://localhost:1421,http://localhost:1235

      PROJECT_ID: d2c17132-71a5-4785-9188-9c519ab38bf3
      PROJECT_API_KEY: nRweOaZEMyuKLrwMPieAXmWViYsxkDLtynIKecwKQMLyCIcTsDvglJMPYGcpYPjx
      PROJECT_SPEC: ${PROJECT_SPEC:-http://backend:3000/openapi.json}
      PROJECT_API_URL: ${PROJECT_API_URL:-http://backend:3000}

      JWKS_URL: http://localhost:3100/api/auth/jwks
      TOKEN_ISSUER: http://localhost:3100
      TOKEN_AUDIENCE: http://localhost:3000
    env_file:
      - apps/backend/.env
    ports:
      - '3000:3000'
    healthcheck:
      test: 'wget --no-verbose --spider --tries=1 http://localhost:3000/health || exit 1'
    networks:
      - app_network
    depends_on:
      migration:
        condition: service_completed_successfully
      database:
        condition: service_healthy
  migration:
    build:
      context: /Users/ezzabuzaid/Desktop/mo/pm
      dockerfile: /Users/ezzabuzaid/Desktop/mo/pm/Dockerfile.migration
    platform: linux/amd64
    depends_on:
      database:
        condition: service_healthy
    environment:
      CONNECTION_STRING: 'postgresql://youruser:yourpassword@database:5432/march'
    networks:
      - app_network

  database:
    image: postgres:18
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_USER: 'youruser'
      POSTGRES_DB: 'march'
      PGDATA: /var/lib/postgresql/18/data
    volumes:
      - pgdata18:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'youruser', '-d', 'march']
    networks:
      - app_network
networks:
  app_network:

volumes:
  pgdata18: {}
